---

  - name: parse sources
    mssql_users_source:
      sources: '{{ sources }}'
    delegate_to: localhost

  - name: synchronization logins, users, roles
    mssql_users:
      connection:
        host: '{{ mssql_host }}'
        port: '{{ mssql_host_port | default(1433) }}'
        login: '{{ mssql_login }}'
        password: '{{ mssql_password }}'
      sql_login: '{{ item.value }}'
    delegate_to: localhost
    register: sql_result
    loop: "{{ ansible_facts.sql_logins|dict2items }}"
    loop_control:
      label: ">[LOGIN]: [{{ item.key }}]{% if sql_result.changed %}\n\n[CHANGES]:\n           {{ sql_result.changes | join('\n           ') }}{% endif %}{% if sql_result.sql_info is defined and sql_result.sql_info|length > 0%}\n\n[INFO]:\n           {{ sql_result.sql_info | join('\n           ') }}{% endif %}{% if sql_result.sql_warnings is defined and sql_result.sql_warnings|length > 0%}\n\n[WARNINGS]:\n           {{ sql_result.sql_warnings | join('\n           ') }}{% endif %}{% if sql_result.sql_errors is defined and sql_result.sql_errors|length > 0%}\n\n[ERRORS]:\n           {{ sql_result.sql_errors | join('\n           ') }}{% endif %}{% if sql_result.msg is defined and sql_result.msg %}\n\n[MODULE_ERROR]: [{{ sql_result.msg }}]\n{% endif %}{% if (sql_result.msg is defined and sql_result.msg) or (sql_result.sql_warnings is defined and sql_result.sql_warnings|length > 0) or (sql_result.sql_info is defined and sql_result.sql_info|length > 0) or (sql_result.sql_warnings is defined and sql_result.sql_warnings|length > 0) %}\n\n{% endif %}"